config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /fr|en/ do
    devise_for :users

    mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

    # Defines the root path route ("/")
    # root "articles#index"
    root to: "pages#home"
    # with namespace admin, all the resource routes will be prefixed with the same
    # starting path /admin
    namespace :admin do
      get '/', to: "admin#index"

      resources :questions do
        resources :answers, only: [:edit, :update]
      end

      resources :lexicons do
        resources :lexicon_answers, only: [:edit, :update]
      end

      resources :lexicons_results, only: [:index]
    end

    get "/ressources", to: "pages#ressources"
    get "qcm", to: "questions#qcm"
    get "/missed_questions", to: "questions#missed_questions"

    resources :questions, only: [:index]  do
      member do
        get 'add_failed_question'
        get 'destroy_failed_question'
      end
      collection do
        post 'add_failed_questions'
        post 'destroy_failed_questions'
      end
    end

    resources :lexicons, only: [:index] do
      # url /lexicons/qcm
      collection do
        get "qcm", to: "lexicons#qcm"
        post "add_lexicon_result"
      end
    end
  end
end

app/models/question.rb
# == Schema Information
#
# Table name: questions
#
#  id         :bigint           not null, primary key
#  statement  :text             not null
#  prop_one   :text             not null
#  prop_two   :text             not null
#  prop_three :text             not null
#  level      :integer          not null
#  category   :integer          not null
#  user_id    :bigint           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Question < ApplicationRecord
  belongs_to :user
  has_one :answer, dependent: :destroy
  has_and_belongs_to_many :failed_questions, class_name: 'User', join_table: 'missed_questions'

  accepts_nested_attributes_for :answer, allow_destroy: true

  validates :level, :category, :statement, :prop_one, :prop_two, :prop_three, presence: true
  validates :statement, length: { minimum: 2 }
  validates :prop_one, length: { minimum: 2 }
  validates :prop_two, length: { minimum: 2 }
  validates :prop_three, length: { minimum: 2 }

  enum level: { départemental: 1, régional: 2 }
  enum category: { généralités: 1, fleuret: 2, épée: 3, sabre: 4 }

  scope :dep_g, -> { where(level: 1).where(category: 1)}
  scope :dep_f, -> { where(level: 1).where(category: 2)}
  scope :dep_e, -> { where(level: 1).where(category: 3)}
  scope :dep_s, -> { where(level: 1).where(category: 4)}
  scope :reg_g, -> { where(level: 2).where(category: 1)}
  scope :reg_f, -> { where(level: 2).where(category: 2)}
  scope :reg_e, -> { where(level: 2).where(category: 3)}
  scope :reg_s, -> { where(level: 2).where(category: 4)}

  def self.filter_by_level(level)
    where(level: level)
  end

  def self.filter_by_category(category)
    where(category: category)
  end

end

app/controllers/admin/questions_controller.rb
# frozen_string_literal = true

# controller for admin questions
module Admin
  class QuestionsController < ApplicationController
    before_action :set_question, only: [:show, :edit, :update, :destroy]

    def index
      current_user.contributor? ? @questions = Question.where(user_id: current_user) : @questions = Question.all
      @questions_dep_g = @questions.dep_g
      @questions_dep_f = @questions.dep_f
      @questions_dep_e = @questions.dep_e
      @questions_dep_s = @questions.dep_s
      @questions_reg_g = @questions.reg_g
      @questions_reg_f = @questions.reg_f
      @questions_reg_e = @questions.reg_e
      @questions_reg_s = @questions.reg_s
      authorize([:admin, :question])
    end

    def show
    end

    def new
      @user = current_user
      @question = Question.new
      # build associated answer to get it in the form
      @question.build_answer
      @question.user = @user
      authorize @question
    end

    def create
      @user = current_user
      @question = Question.new(question_params)
      @question.user = @user
      authorize @question
      if @question.save
        redirect_to admin_question_path(@question)
      else
        render :new, status: :unprocessable_entity
      end
    end

    def edit
      @answer = @question.answer
    end

    def update
      if @question.update(question_params)
        redirect_to admin_question_path(@question)
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @question.destroy
      redirect_to admin_questions_path
    end

    private

    def set_question
      @question = Question.find(params[:id])
      authorize @question
    end

    def question_params
      params.require(:question).permit(:statement, :prop_one, :prop_two, :prop_three, :level, :category, answer_attributes: [:id, :explanation, :good_prop, :_destroy])
    end
  end
end

app/controllers/questions_controller.rb
# frozen_string_literal = true

require 'will_paginate/array' #needed to work with arrays

# controller for questions
class QuestionsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :qcm]
  before_action :set_question, only: [:add_failed_question, :destroy_failed_question]

  def index
    @questions = policy_scope(Question).order(created_at: :desc)
    @questions = @questions.filter_by_level(params[:level]) if params[:level].present?
    @questions = @questions.filter_by_category(params[:category]) if params[:category].present?
    @count = @questions.length
    @questions = @questions.paginate(page: params[:page], per_page: 1)
  end

  def qcm
    @level = params[:level]
    @category = params[:category]
    @questions = Question.all.includes(:answer)
    authorize @questions
    @questions_generales = @questions.filter_by_level(@level).where(category: 1).shuffle if @level.present?
    @questions_specifiques = @questions.filter_by_level(@level).filter_by_category(@category).shuffle if @level.present? && @category.present?
    if @level == 'départemental'
      @questions_generales = @questions_generales.first(12)
      @questions_specifiques = @questions_specifiques.first(8)
    else
      @questions_generales = @questions_generales.first(20)
      @questions_specifiques = @questions_specifiques.first(10)
    end
  end

  def missed_questions
    @missed_questions = Question.joins(:failed_questions).where(missed_questions: { user_id: current_user.id }).includes(:answer)
    @count = @missed_questions.length
    authorize @missed_questions
  end

  def add_failed_question
    authorize Question

    return unless @question

    current_user.failed_questions << @question if !current_user.failed_questions.include?(@question)
    head :ok # Returns a response that has no content, with status ok
  end

  def destroy_failed_question
    authorize Question

    return unless @question

    current_user.failed_questions.destroy(@question) if current_user.failed_questions.include?(@question)
    head :ok
  end

  def add_failed_questions
    authorize Question
    return unless params[:ids]

    ids = params[:ids].split(',').map(&:to_i)
    # ids est un array avec ttes les mauvaises réponses au qcm
    if ids.present?
      # on enlève les ids qui figurent déjà dans les mauvaises réponses
      # et on ajoute les ids restants à la table de jointure
      Question.where(id: ids)
              .reject { |question| current_user.failed_questions.include?(question) }
              .map { |question| current_user.failed_questions << question }
    end
    head :ok
  end

  def destroy_failed_questions
    authorize Question
    return unless params[:ids]

    # ids est un array avec ttes les bonnes réponses au qcm
    ids = params[:ids].split(',').map(&:to_i)
    if ids.present?
      # on select les ids qui figurent dans la table de jointure
      # et on les enlève de la table
      Question.where(id: ids)
              .select { |question| current_user.failed_questions.include?(question) }
              .map { |question| current_user.failed_questions.destroy(question) }
    end
    head :ok
  end

  private

  def set_question
    @question = Question.find(params[:id])
    authorize @question
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_answer_form.html.erb
<div class="nested-form-wrapper" data-new-record="<%= field.object.new_record? %>">
  <p class="font-semibold my-4">Bonne réponse :</p>
  <div class="flex flex-col">
    <div class="flex justify-between items-center w-1/4">
      <%= field.label :answer_one, "Réponse une", class: "ml-4" %>
      <%= field.radio_button :good_prop, "un" %>
    </div>
    <div class="flex justify-between items-center w-1/4">
      <%= field.label :answer_two, "Réponse deux", class: "ml-4" %>
      <%= field.radio_button :good_prop, "deux" %>
    </div>
    <div class="flex justify-between items-center w-1/4 mb-4">
      <%= field.label :answer_three, "Réponse trois", class: "ml-4" %>
      <%= field.radio_button :good_prop, "trois" %>
    </div>
  </div>
  <%= field.label :explanation, "Explication de la réponse" %>
  <%= field.text_field :explanation, class: "w-full" %>
  <%= field.hidden_field :_destroy %>
</div>

app/views/questions/_form.html.erb
<%= form_with model: @question, data: { controller: 'nested-form', nested_form_wrapper_selector_value: '.nested-form-wrapper' },
html: { style: "display:flex; flex-direction:column;font-size:1rem;"} do |f| %>
  <% if @question.errors.any? %>
    <div class="error-message">
      <p style="color:red"><%= @question.errors.full_messages.to_sentence.capitalize %></p>
    </div>
  <% end %>
  <p class="font-semibold my-4">Niveau :</p>
  <div class="flex justify-between items-center w-1/4">
    <%= f.label :level, "Départemental", class: "ml-4" %>
    <%= f.radio_button :level, "départemental" %>
  </div>
  <div class="flex justify-between items-center w-1/4">
    <%= f.label :level, "Régional", class: "ml-4" %>
    <%= f.radio_button :level, "régional" %>
  </div>
  <p class="font-semibold my-4">Catégorie :</p>
  <div class="flex justify-between items-center w-1/4">
    <%= f.label :category, "Généralités", class: "ml-4" %>
    <%= f.radio_button :category, "généralités" %>
  </div>
  <div class="flex justify-between items-center w-1/4">
    <%= f.label :category, "Fleuret", class: "ml-4" %>
    <%= f.radio_button :category, "fleuret" %>
  </div>
  <div class="flex justify-between items-center w-1/4">
    <%= f.label :category, "Épée", class: "ml-4" %>
    <%= f.radio_button :category, "épée" %>
  </div>
  <div class="flex justify-between items-center w-1/4">
    <%= f.label :category, "Sabre", class: "ml-4" %>
    <%= f.radio_button :category, "sabre" %>
  </div>

  <%= f.label :statement, "Énoncé de la question", class: "mt-4"%>
  <%= f.text_field :statement %>
  <%= f.label :prop_one, "Réponse une" %>
  <%= f.text_field :prop_one %>
  <%= f.label :prop_two, "Réponse deux" %>
  <%= f.text_field :prop_two %>
  <%= f.label :prop_three, "Réponse trois" %>
  <%= f.text_field :prop_three %>
  <template data-nested-form-target="template">
    <%= f.fields_for :answer, Answer.new, child_index: 'NEW_RECORD' do |answer_fields| %>
      <%= render "answer_form", field: answer_fields %>
    <% end %>
  </template>
  <%= f.fields_for :answer do |answer_fields| %>
    <%= render "answer_form", field: answer_fields %>
  <% end %>
  <%= f.submit "Valider", class: "text-white bg-darkblue text-lg p-2 rounded self-center mt-4" %>
<% end %>
<%= link_to "Back", :back, class: "text-white bg-darkblue text-lg p-2 rounded" %>

app/views/questions/dashboard.html.erb
<section class="w-8/12 mx-auto my-10 text-lg">
  <div class="mb-4">
    <h3 class="mb-4 font-bold text-xl">Niveau Départemental</h3>
      <h4 class="mb-4 font-semibold">Généralités</h4>
        <% @questions_dep_g.each do |question| %>
          <ul class="flex justify-between items-center ml-4">
              <li><i class="fas fa-check mr-2"></i><%= question.statement.first(100) %>...</li><%= link_to '<i class="fas fa-expand"></i>'.html_safe, question_path(question), title: "Voir" %>
          </ul>
        <% end %>
      <h4 class="mb-4 font-semibold">Fleuret</h4>
        <% @questions_dep_f.each do |question| %>
          <ul class="flex justify-between items-center ml-4">
              <li><i class="fas fa-check mr-2"></i><%= question.statement.first(100) %>...</li><%= link_to '<i class="fas fa-expand"></i>'.html_safe, question_path(question), title: "Voir" %>
          </ul>
        <% end %>
      <h4 class="mb-4 font-semibold">Épée</h4>
        <% @questions_dep_e.each do |question| %>
          <ul class="flex justify-between items-center ml-4">
              <li><i class="fas fa-check mr-2"></i><%= question.statement.first(100) %>...</li><%= link_to '<i class="fas fa-expand"></i>'.html_safe, question_path(question), title: "Voir" %>
          </ul>
        <% end %>
      <h4 class="mb-4 font-semibold">Sabre</h4>
        <% @questions_dep_s.each do |question| %>
          <ul class="flex justify-between items-center ml-4">
              <li><i class="fas fa-check mr-2"></i><%= question.statement.first(100) %></li><%= link_to '<i class="fas fa-expand"></i>'.html_safe, question_path(question), title: "Voir" %>
          </ul>
        <% end %>
  </div>
  <div class="dashboard-reg">
    <h3 class="mb-4 font-bold text-xl">Niveau Régional</h3>
      <h4 class="mb-4 font-semibold">Généralités</h4>
        <% @questions_reg_g.each do |question| %>
          <ul class="flex justify-between items-center ml-4">
              <li><i class="fas fa-check mr-2"></i><%= question.statement.first(100) %>...</li><%= link_to '<i class="fas fa-expand"></i>'.html_safe, question_path(question), title: "Voir" %>
          </ul>
        <% end %>
      <h4 class="mb-4 font-semibold">Fleuret</h4>
        <% @questions_reg_f.each do |question| %>
          <ul class="flex justify-between items-center ml-4">
              <li><i class="fas fa-check mr-2"></i><%= question.statement.first(100) %>...</li><%= link_to '<i class="fas fa-expand"></i>'.html_safe, question_path(question), title: "Voir" %>
          </ul>
        <% end %>
      <h4 class="mb-4 font-semibold">Épée</h4>
        <% @questions_reg_e.each do |question| %>
          <ul class="flex justify-between items-center ml-4">
              <li><i class="fas fa-check mr-2"></i><%= question.statement.first(100) %>...</li><%= link_to '<i class="fas fa-expand"></i>'.html_safe, question_path(question), title: "Voir" %>
          </ul>
        <% end %>
      <h4 class="mb-4 font-semibold">Sabre</h4>
        <% @questions_reg_s.each do |question| %>
          <ul class="flex justify-between items-center ml-4">
              <li><i class="fas fa-check mr-2"></i><%= question.statement.first(100) %>...</li><%= link_to '<i class="fas fa-expand"></i>'.html_safe, question_path(question), title: "Voir" %>
          </ul>
        <% end %>
  </div>
</section>

app/views/questions/index.html.erb
<% content_for :meta_title, "Arbire d'escrime - Questions" %>
<% content_for :meta_description, "Entraînes-toi avec le type de questions sélectionné" %>

<section data-controller="validate-question" class="w-11/12 md:w-8/12 mx-auto my-10 text-lg">
<% @questions.each do |question| %>
  <h3 class="italic"><%= @count %> questions de niveau <%= question.level %>, catégorie <%= question.category %></h3>
  <form data-question-id=<%= question.id %> class="question-index-forms flex flex-col mt-8">
    <legend class="mb-4"><%= question.statement %> :</legend>
    <label>
      <input data-validate-question-target="input" name="question" type="radio" value="<%= question.prop_one %>" data-value="un">
      <%= question.prop_one %>
    </label>
    <label>
      <input data-validate-question-target="input" name="question" type="radio" value="<%= question.prop_two %>" data-value="deux">
      <%= question.prop_two %>
    </label>
    <label>
      <input data-validate-question-target="input" name="question" type="radio" value="<%= question.prop_three %>" data-value="trois">
      <%= question.prop_three %>
    </label>
    <button data-action="click->validate-question#showAnswer" data-validate-question-target="btn" class="self-center text-white bg-darkblue text-lg p-2 rounded mt-4" >Valider</button>
  </form>
  <div data-validate-question-target="answerdiv" class="hidden">
    <p data-validate-question-target="goodanswer" class="hidden">La bonne réponse est la réponse <%= question.answer.good_prop %>.</p>
    <p data-validate-question-target="explanation" data-value="<%= question.answer.good_prop %>"><%= question.answer.explanation %>.</p>
  </div>
<% end %>
<%= will_paginate @questions, class: "apple_pagination" %>
</section>

app/views/questions/missed_questions.html.erb
<% content_for :meta_title, "Arbire d'escrime - Questions à revoir" %>
<% content_for :meta_description, "Entraînes-toi avec des questions auxquelles tu as mal répondu" %>

<section data-controller="missed-results">
  <div class="flex flex-col w-11/12 md:w-8/12 mx-auto my-10">
    <% if @missed_questions.blank? %>
      <h2 class="w-full mx-auto text-center mt-24">Il n'y a pas de questions auxquelles vous auriez répondu de manière incorrecte, bravo 🙌</h2>
      <!-- Lien de retour à l'accueil si pas de mauvaise réponse -->
      <%= link_to "Retour à l'accueil", root_path, class: "self-center mt-8 text-white bg-darkblue text-lg p-2 rounded" %>
    <% else %>
      <h2 data-missed-results-target="countGeneral" data-count=<%= @count %> class="font-bold text-lg"><%= @count %> <%= "question".pluralize(@count) %> à revoir</h2>
      <div class="qcm-general-questions text-lg" data-missed-questions="<%= @missed_questions.pluck(:id)%>" >
        <% @missed_questions.each_with_index do |question, index| %>
          <form data-missed-results-target="formGeneral" class="flex flex-col text-justify" data-index="<%= index %>" data-good-answer="<%= question.answer.good_prop %>" data-question-id=<%= question.id %>>
            <legend class="mt-8 italic"><%= question.statement %> :</legend>
            <label>
              <input name="question-general-<%= index %>" type="radio" value="un">
              <%= question.prop_one %>
            </label>
            <label>
              <input name="question-general-<%= index %>" type="radio" value="deux">
              <%= question.prop_two %>
            </label>
            <label>
              <input name="question-general-<%= index %>" type="radio" value="trois">
              <%= question.prop_three %>
            </label>
            <div data-missed-results-target="answer" class="italic text-justify mt-4 hidden">
              <p class="hidden mb-2">La bonne réponse est la réponse <%= question.answer.good_prop %>.</p>
              <p><%=  question.answer.explanation %>.</p>
            </div>
          </form>
        <% end %>
      </div>
      <button data-action="click->missed-results#handleSubmit" data-missed-results-target="submitbtn" class="self-center mt-8 text-white bg-darkblue text-lg p-2 rounded validate-qcm">Valider les réponses</button>
    <% end %>
    <%= link_to "Retour à l'accueil", root_path, data: { missed_results_target: "homeLink"}, class: "self-center mt-8 text-white bg-darkblue text-lg p-2 rounded hidden" %>
    <!-- Modal -->
    <div data-missed-results-target="modalDiv" class="p-4 hidden z-20 bg-gray-300 text-lg" id="modal_id" tabindex="-1" role="dialog" aria-labelledby="modal_id" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content flex flex-col ">
          <div class="flex justify-between items-center mb-4">
            <h5 class="font-semibold " id="modal_id">Résultat</h5>
            <button data-action="click->missed-results#close" type="button" class="text-xl text-white bg-gray-500 rounded px-2" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div data-missed-results-target="modalBody" class="flex flex-col items-center mb-12"></div>
          <div class="modal-footer flex flex-col md:flex-row justify-between items-center">
            <button data-qcm-results-target="correctionbtn" data-action="click->missed-results#handleCorrection" type="button" class="mb-4 md:mb-0 text-white bg-darkblue text-lg p-2 rounded correction-qcm" data-bs-dismiss="modal">Voir la correction des questions</button>
            <%= link_to "Retour à la page d'accueil", root_path, class: "text-white bg-darkblue text-lg p-2 rounded" %>
          </div>
          </div>
        </div>
      </div>
    </div>
    <!-- fin modal -->
  </div>
</section>

app/views/questions/qcm.html.erb
<% content_for :meta_title, "Arbire d'escrime - Qcm" %>
<% content_for :meta_description, "Qcm d'entraînement chronométré" %>

<section data-controller="qcm-results">
  <%= render 'shared/timer' %>
  <div data-qcm-results-target="qcmContainer" class="flex flex-col w-11/12 md:w-8/12 mx-auto my-10">
    <h2 data-qcm-results-target="qcmTitle" data-level="<%= @level %>" class="text-xl font-bold">Qcm <%= @level == "départemental" ? 'départemental' : 'régional' %>
     spécifique
     <% if @category == "fleuret" %>
      fleuret
     <% elsif @category == "épée" %>
      épée
      <% else %>
      sabre
      <% end %>
    </h2>
    <div class="qcm-general-questions text-lg" data-questions-gen="<%= @questions_generales.pluck(:id)%>" >
      <h3 class="font-semibold my-8">Questions générales</h3>
        <% @questions_generales.each_with_index do |question, index| %>
          <form data-qcm-results-target="formGeneral" class="flex flex-col text-justify" data-index="<%= index %>" data-good-answer="<%= question.answer.good_prop %>" data-question-id=<%= question.id %>>
            <legend class="mt-8 italic"><%= question.statement %> :</legend>
            <label>
              <input name="question-general-<%= index %>" type="radio" value="un">
              <%= question.prop_one %>
            </label>
            <label>
              <input name="question-general-<%= index %>" type="radio" value="deux">
              <%= question.prop_two %>
            </label>
            <label>
              <input name="question-general-<%= index %>" type="radio" value="trois">
              <%= question.prop_three %>
            </label>
            <div data-qcm-results-target="answer" class="italic text-justify mt-4 hidden">
              <p class="hidden mb-2">La bonne réponse est la réponse <%= question.answer.good_prop %>.</p>
              <p><%=  question.answer.explanation %>.</p>
            </div>
          </form>
        <% end %>
    </div>
    <div class="qcm-specific-questions text-lg" data-questions-spe="<%= @questions_specifiques.pluck(:id)%>" >
      <h3 class="font-semibold my-8">Question spécifiques</h3>
        <% @questions_specifiques.each_with_index do |question, index| %>
          <form data-qcm-results-target="formSpecific" class="flex flex-col text-justify" data-index="<%= index %>" data-good-answer="<%= question.answer.good_prop %>" data-question-id=<%= question.id %>>
            <legend class="mt-8 italic"><%= question.statement %> :</legend>
            <label>
              <input name="question-specific-<%= index %>" type="radio" value="un">
              <%= question.prop_one %>
            </label>
            <label>
              <input name="question-specific-<%= index %>" type="radio" value="deux">
              <%= question.prop_two %>
            </label>
            <label>
              <input name="question-specific-<%= index %>" type="radio" value="trois">
              <%= question.prop_three %>
            </label>
            <div data-qcm-results-target="answer" class="italic text-justify mt-4 hidden">
              <p class="hidden mb-2">La bonne réponse est la réponse <%= question.answer.good_prop %>.</p>
              <p><%= question.answer.explanation %>.</p>
            </div>
          </form>
        <% end %>
    </div>
    <button data-action="click->qcm-results#handleSubmit" data-qcm-results-target="submitbtn" class="self-center mt-8 text-white bg-darkblue text-lg p-2 rounded validate-qcm">Valider les réponses</button>
    <!-- Lien de retour à l'accueil quand le user a regardé la correction du qcm -->
    <%= link_to "Retour à l'accueil", root_path, data: { qcm_results_target: "homeLink"}, class: "self-center mt-8 text-white bg-darkblue text-lg p-2 rounded hidden" %>
    <!-- Modal -->
    <div data-qcm-results-target="modalDiv" class="p-4 hidden z-20 bg-gray-300 text-lg" id="modal_id" tabindex="-1" role="dialog" aria-labelledby="modal_id" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content flex flex-col ">
          <div class="flex justify-between items-center mb-4">
            <h5 class="font-semibold " id="modal_id">Résultat</h5>
            <button data-action="click->qcm-results#close" type="button" class="text-xl text-white bg-gray-500 rounded px-2" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div data-qcm-results-target="modalBody" class="flex flex-col items-center mb-12"></div>
          <div class="modal-footer flex flex-col md:flex-row justify-between items-center">
            <button data-qcm-results-target="correctionbtn" data-action="click->qcm-results#handleCorrection" type="button" class="mb-4 md:mb-0 text-white bg-darkblue text-lg p-2 rounded correction-qcm" data-bs-dismiss="modal">Voir la correction du QCM</button>
            <%= link_to "Retour à la page d'accueil", root_path, class: "text-white bg-darkblue text-lg p-2 rounded" %>
            <!--<button type="button" class="text-white bg-darkblue text-lg p-2 rounded homepage-qcm" data-bs-dismiss="modal">Retour à la page d'accueil</button>-->
          </div>
          </div>
        </div>
      </div>
    </div>
    <!-- fin modal -->
  </div>
</section>

app/views/questions/show.html.erb
<div class="flex flex-col w-8/12 mx-auto my-8">
  <h3 class="font-semibold text-2xl">Question de niveau <%= @question.level %>, catégorie <%= @question.category %></h3>
  <h4 class="my-8 text-xl"><%= @question.statement %> :</h4>
    <ul class="w-full italic text-justify text-lg">
      <li><%= @question.prop_one %></li>
      <li><%= @question.prop_two %></li>
      <li><%= @question.prop_three %></li>
    </ul>
  <h4 class="my-8 text-lg">La bonne réponse est la réponse <%= @question.answer.good_prop %>.</h4>
  <p class="text-justify text-lg"><%= @question.answer.explanation %>.</p>
  <div class="flex justify-evenly mt-8">
    <%= link_to "Modifier",  edit_question_path(@question), class: "text-white bg-darkblue text-lg p-2 rounded" %>
    <%= link_to "Supprimer", question_path(@question), data: {  turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "text-white bg-darkblue text-lg p-2 rounded" %>
  </div>
</div>