config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /fr|en/ do
    devise_for :users

    mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

    # Defines the root path route ("/")
    # root "articles#index"
    root to: "pages#home"
    # with namespace admin, all the resource routes will be prefixed with the same
    # starting path /admin
    namespace :admin do
      get '/', to: "admin#index"

      resources :questions do
        resources :answers, only: [:edit, :update]
      end

      resources :lexicons do
        resources :lexicon_answers, only: [:edit, :update]
      end

      resources :lexicons_results, only: [:index]
    end

    get "/ressources", to: "pages#ressources"
    get "qcm", to: "questions#qcm"
    get "/missed_questions", to: "questions#missed_questions"

    resources :questions, only: [:index]  do
      member do
        get 'add_failed_question'
        get 'destroy_failed_question'
      end
      collection do
        post 'add_failed_questions'
        post 'destroy_failed_questions'
      end
    end

    resources :lexicons, only: [:index] do
      # url /lexicons/qcm
      collection do
        get "qcm", to: "lexicons#qcm"
        post "add_lexicon_result"
      end
    end
  end
end

app/views/shared/_banner.html.erb
<div class="flex justify-between items-center md:items-stretch md:w-screen h-fit md:h-30vh xl:h-40vh bg-darkblue">
  <div class="flex flex-col justify-center items-center m-4 w-full md:justify-around md:w-1/3">
    <h1 class="text-center text-white text-2xl font-bold">S'ENTRAÎNER AU QCM D'ARBITRAGE</h1>
    <div class="flex flex-col justify-between h-1/4">
      <h2 class="text-white text-center font-bold text-xl opacity-80">FLEURET - ÉPÉE - SABRE</h2>
      <h2 class="text-white text-center font-bold text-xl opacity-80">DÉPARTEMENTAL - RÉGIONAL</h2>
    </div>
  </div>
  <div class="hidden md:block bg-banner bg-contain bg-left w-2/3 h-auto"></div>
  <%#= image_tag 'banner.jpg', class: "banner-img" %>
</div>

app/views/shared/_flashes.html.erb
<div data-controller="flashes" id="flash"><!-- id flash added for create.turbo_stream -->
  <% if notice %>
    <div data-flashes-target="flash" class="flex justify-between items-center absolute z-10 inset-x-40 bg-blue-100 rounded my-8 border-blue-800 border-2 mx-auto p-4 text-blue-800 font-semibold w-6/12 " role="notice">
      <%= notice %>
      <button type="button" data-action="click->flashes#close" class="text-blue-600 hover:text-blue-900" aria-label="Close">X</button>
    </div>
  <% end %>
  <% if alert %>
    <div data-flashes-target="flash" class="flex justify-between items-center absolute z-10 inset-x-40 bg-red-100 rounded border-red-800 border-2 my-8 mx-auto p-4 text-red-800 font-semibold w-6/12" role="alert">
      <%= alert %>
      <button type="button" data-action="click->flashes#close" class="text-red-600 hover:text-red-900" aria-label="Close">X</button>
    </div>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<footer class="flex justify-around items-center bg-darkblue w-screen h-fit md:h-10vh text-white">
  <div class="w-full mx-auto grid grid-rows-3 lg:grid-rows-1 lg:grid-cols-3">
    <div class=" flex justify-center mb-4 lg:justify-start md:mb-0 md:ml-8">
      <%= link_to "Escrime Ile De France", "https://escrime-iledefrance.fr", target: :blank %>
    </div>
    <div class=" flex justify-center mb-4 md:mb-0">
      <%= link_to "Escrime IDF Ouest", "https://www.escrime-idfouest.fr", target: :blank %>
      <%= link_to "Escrime IDF Paris", "https://escrimeaparis.fr", class: "ml-6", target: :blank %>
      <%= link_to "Escrime IDF Est", "https://www.escrime-idfest.fr", class: "ml-6", target: :blank %>
    </div>
    <p class="inline-block italic justify-self-center lg:justify-self-end md:mr-10"><%= mail_to "contact@escrime-qcm-arbitrage.com", "Contacter l'administratrice du site" %></p>
  </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<navbar class=" flex flex-col items-center justify-between bg-white w-screen h-20vh flex-wrap md:h-10vh xl:flex-row  xl:flex-nowwrap">
    <div class="flex items-center justify-center flex-wrap xl:justify-start xl:flex-nowwrap">
      <%= image_tag "nav_image.jpg", class: "w-8 h-8 lg:w-12 lg:h-12 mr-4" %>
      <%= link_to "Accueil", root_path, class: "text-darkblue text-xl hover:text-gray-500 hover:font-semibold mr-4" %>
      <!-- id ressources_link for system tests -->
      <%= link_to "Ressources", ressources_path, class: "text-darkblue text-xl hover:text-gray-500 hover:font-semibold mr-4", id: "ressources_link" %>
      <%= link_to "Lexique", lexicons_path, class: "text-darkblue text-xl hover:text-gray-500 hover:font-semibold mr-4" %>
      <% if current_user && (month_beginning && current_user.intern? || current_user.admin?) %>
        <%= link_to "QCM-Lexique", qcm_lexicons_path, class: "text-darkblue text-xl hover:text-gray-500 hover:font-semibold mr-4" %>
      <% end %>
      <%= mail_to "contact@escrime-qcm-arbitrage.com", "Contact", class: "text-darkblue text-xl hover:text-gray-500 hover:font-semibold mr-4" %>
    </div>
    <!--<ul data-controller="secret-code" class="flex items-center justify-start w-fit"> -->
    <ul class="flex items-center justify-center h-8 lg:h-12 xl:justify-start w-fit">
      <% if user_signed_in? && (current_user.admin? || current_user.contributor?) %>
        <li><%= link_to "Dashboard", admin_path, class: "text-darkblue text-xl hover:text-gray-500 hover:font-semibold mr-4" %></li>
        <li><%= link_to "Déconnexion", destroy_user_session_path, data: { turbo_method: :delete }, class: "text-darkblue text-xl hover:text-gray-500 hover:font-semibold mr-4" %></li>
      <% elsif user_signed_in? %>
        <li><%= link_to "Déconnexion", destroy_user_session_path, data: { turbo_method: :delete }, class: "text-darkblue text-xl hover:text-gray-500 hover:font-semibold mr-4" %></li>
      <% else %>
        <li class="flex justify-between items-center">
          <%= link_to "Connexion", new_user_session_path, class: "text-darkblue text-xl hover:text-gray-500 hover:font-semibold mr-4" %>
        </li>
        <li class="flex justify-between items-center">
          <%= link_to "Créer un compte", new_user_registration_path, class: "text-darkblue text-xl hover:text-gray-500 hover:font-semibold mr-4" %>
        </li>
      <% end %>
    </ul>
</navbar>

app/views/shared/_timer.html.erb
<% if controller.controller_name == "lexicons" %>
  <aside data-qcm-lexicon-target="timerDiv" class="bg-gray-500 flex justify-center items-center w-full fixed top-[20vh] md:top-[10vh]">
    <p class="p-1 text-base"><i class="fas fa-clock"></i></p>
    <p class="p-1"><span data-qcm-lexicon-target="min" ></span> min</p>
    <p class="p-1"><span data-qcm-lexicon-target="sec"></span> sec</p>
  </aside>
<% else %>
  <aside data-qcm-results-target="timerDiv" class="bg-gray-500 flex justify-center items-center w-full fixed top-[20vh] md:top-[10vh]">
    <p class="p-1 text-base"><i class="fas fa-clock"></i></p>
    <p class="p-1"><span data-qcm-results-target="min" ></span> min</p>
    <p class="p-1"><span data-qcm-results-target="sec"></span> sec</p>
  </aside>
<% end %>