config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /fr|en/ do
    devise_for :users

    mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

    # Defines the root path route ("/")
    # root "articles#index"
    root to: "pages#home"
    # with namespace admin, all the resource routes will be prefixed with the same
    # starting path /admin
    namespace :admin do
      get '/', to: "admin#index"

      resources :questions do
        resources :answers, only: [:edit, :update]
      end

      resources :lexicons do
        resources :lexicon_answers, only: [:edit, :update]
      end

      resources :lexicons_results, only: [:index]
    end

    get "/ressources", to: "pages#ressources"
    get "qcm", to: "questions#qcm"
    get "/missed_questions", to: "questions#missed_questions"

    resources :questions, only: [:index]  do
      member do
        get 'add_failed_question'
        get 'destroy_failed_question'
      end
      collection do
        post 'add_failed_questions'
        post 'destroy_failed_questions'
      end
    end

    resources :lexicons, only: [:index] do
      # url /lexicons/qcm
      collection do
        get "qcm", to: "lexicons#qcm"
        post "add_lexicon_result"
      end
    end
  end
end

app/views/pages/home.html.erb
<% content_for :meta_title, "Arbitre d'escrime - Accueil" %>
<% content_for :meta_description, "Bienvenue sur le site d'entraînement au QCM d'arbitrage à l'escrime" %>
<section data-controller="homepage-btns" class="w-11/12 md:w-8/12 mx-auto my-10">
  <div data-homepage-btns-target="paragraph" class="flex flex-col w-full text-lg text-justify">
    <p>L'objectif de ce site est de vous permettre de vous entraîner au qcm d'arbitrage,
    première étape pour entrer en formation d'arbitre départemental ou régional.</p>
    <p class="mt-4">Nous vous conseillons vivement de lire au préalable les différents documents disponibles
    dans la rubrique <%= link_to "Ressources", ressources_path, class: "italic hover:font-semibold" %>.</p>
    <p class="mt-4">Vous avez la possibilité soit de sélectionner un type de questions, soit de passer un
    qcm complet chronométré (20 min pour le départemental, 30 minutes pour le régional).</p>
    <p class="mt-4">En vous créant un compte, vous aurez la possibilité de revoir en particulier les questions auxquelles
       vous auriez mal répondu.</p>
    <p class="mt-4">Enfin, vous pouvez spécifiquement réviser le vocabulaire de l'escrime <%= link_to "ici", lexicons_path, class: "italic hover:font-semibold" %>, afin d'employer les bons termes lors
      de l'analyse de la phrase d'armes, ou si vous vous préparez aux diplômes fédéraux d'animateur/éducateur.</p>
    <p class="italic mt-4">Bon entraînement !</p>
    <div class="flex flex-col items-center justify-between lg:flex-row w-full my-10">
      <button data-homepage-btns-target="questions" data-action="click->homepage-btns#showQuestions" class="w-full mb-2 lg:mb-0 lg:w-fit text-white bg-darkblue text-lg p-2 rounded">Sélectionner des questions</button>
      <button data-homepage-btns-target="qcm" data-action="click->homepage-btns#showQcm" class="w-full mb-2 lg:mb-0 lg:w-fit text-white bg-darkblue text-lg p-2 rounded">QCM complet chronométré</button>
      <% if user_signed_in? %>
        <%= link_to "Revoir les questions où j'ai mal répondu", missed_questions_path, class: "w-full lg:w-fit text-center text-white bg-darkblue text-lg p-2 rounded" %>
      <% end %>
    </div>
  </div>
  <!-- au clic sur selectionner des questions -->
  <div data-homepage-btns-target="questionchoice" class="filters-questions hidden">
    <h2 class="font-semibold text-2xl">Choix du type de questions</h2>
    <%= form_with(url: questions_path, method: 'get', local: true, class: "flex flex-col w-full mt-8") do %>
        <div class="flex justify-between items-start w-full mb-8">
          <div class="flex flex-col w-2/5">
            <h3 class="text-xl mb-4">Catégorie :</h3>
            <div class="flex flex-col text-lg">
              <div class="flex justify-between items-center w-full">
                <%= label_tag "questions-category-general", 'Généralités' %>
                <%= radio_button_tag 'category', 'généralités', false, required: true %>
              </div>
              <div class="flex justify-between items-center w-full">
                <%= label_tag "questions-category-fleuret", 'Spécifique fleuret' %>
                <%= radio_button_tag 'category', 'fleuret', false, required: true %>
              </div>
              <div class="flex justify-between items-center w-full">
                <%= label_tag "questions-category-epee", 'Spécifique épée' %>
                <%= radio_button_tag 'category', 'épée', false, required: true %>
              </div>
              <div class="flex justify-between items-center w-full">
                <%= label_tag "questions-category-sabre", 'Spécifique sabre' %>
                <%= radio_button_tag 'category', 'sabre', false, required: true %>
              </div>
            </div>
          </div>
          <div class="flex flex-col w-2/5">
            <h3 class="text-xl mb-4">Niveau :</h3>
            <div class="question-level-inputs text-lg">
              <div class="flex justify-between items-center w-full">
                <%= label_tag "questions-level-dep", 'Départemental' %>
                <%= radio_button_tag 'level', 'départemental', false, required: true %>
              </div>
              <div class="flex justify-between items-center w-full">
                <%= label_tag "questions-level-reg", 'Régional' %>
                <%= radio_button_tag 'level', 'régional', false, required: true %>
              </div>
            </div>
          </div>
        </div>
        <div class="flex justify-around">
          <%= submit_tag 'Commencer', class: 'text-white bg-darkblue text-lg p-2 rounded submit-questions-choice cursor-pointer' %>
          <%= link_to "Annuler", root_path, class: "text-white bg-darkblue text-lg p-2 rounded" %>
        </div>
      <% end %>
  </div>
  <!-- au clic sur qcm complet -->
  <div data-homepage-btns-target="qcmchoice" class="filters-questions-qcm hidden">
    <h2 class="font-semibold text-2xl">Choix du type de QCM</h2>
    <%= form_with(url: qcm_path, method: 'get', local: true, class: "flex flex-col w-full mt-8") do %>
        <div class="flex justify-between items-start w-full mb-8">
          <div class="flex flex-col w-2/5">
            <h3 class="text-xl mb-4">Catégorie :</h3>
            <div class="flex flex-col text-lg">
              <div class="flex justify-between items-center w-full">
                <%= label_tag "questions-category-fleuret", 'Fleuret' %>
                <%= radio_button_tag 'category', 'fleuret', false, required: true %>
              </div>
              <div class="flex justify-between items-center w-full">
                <%= label_tag "questions-category-epee", 'Épée' %>
                <%= radio_button_tag 'category', 'épée', false, required: true %>
              </div>
              <div class="flex justify-between items-center w-full">
                <%= label_tag "questions-category-sabre", 'Sabre' %>
                <%= radio_button_tag 'category', 'sabre', false, required: true %>
              </div>
            </div>
          </div>
          <div class="flex flex-col w-2/5">
            <h3 class="text-xl mb-4">Niveau :</h3>
            <div class="question-level-inputs text-lg">
              <div class="flex justify-between items-center w-full">
                <%= label_tag "questions-level-dep", 'Départemental' %>
                <%= radio_button_tag 'level', 'départemental', false, required: true  %>
              </div>
              <div class="flex justify-between items-center w-full">
                <%= label_tag "questions-level-reg", 'Régional' %>
                <%= radio_button_tag 'level', 'régional', false, required: true %>
              </div>
            </div>
          </div>
        </div>
        <div class="flex justify-around">
          <%= submit_tag 'Commencer le qcm', class: 'text-white bg-darkblue text-lg p-2 rounded cursor-pointer submit-qcm-choice' %>
          <%= link_to "Annuler", root_path, class: "text-white bg-darkblue text-lg p-2 rounded" %>
        </div>
      <% end %>
  </div>
</section>

app/views/pages/ressources.html.erb
<% content_for :meta_title, "Arbitre d'escrime - Ressources" %>
<% content_for :meta_description, "Tous les documents nécessaires pour réviser la règlementation sur l'escrime" %>
<section class="w-11/12 md:w-8/12 mx-auto my-10 text-darkblue">
  <div class="flex flex-col w-full items-start">
      <h2 class="font-bold text-xl">Documentation à consulter</h2>
      <h3 class="my-8 font-semibold text-lg">International</h3>
      <p class="text-lg">Les règlements internationaux sont consultables sur le
        <%= link_to "site de la FIE", "https://fie.org/fie/documents/rules", target: :blank, class: "italic hover:font-semibold" %>.
        Nous vous conseillons d'y consulter les éléments suivants : le Règlement technique, l'Article t170 (tableau des fautes et sanctions),
        les Règles d'organisation et le Règlement du matériel.
      </p>
      <h3 class="my-8 font-semibold text-lg">National</h3>
        <ul class="fa-ul text-lg">
          <li><span class="fa-li"><i class="fas fa-check"></i></span><%= link_to "Règlements sportifs", "https://www.ffescrime.fr/je-suis-en-club/competiteurs/reglements/", target: :blank, class: "hover:font-semibold"%></li>
          <li><span class="fa-li"><i class="fas fa-check"></i></span><%= link_to "Règlements d'arbitrage", "https://www.ffescrime.fr/je-suis-en-club/arbitres/reglements-arbitrage/", target: :blank, class: "hover:font-semibold"%></li>
        </ul>
      <h3 class="my-8 font-semibold text-lg">IDF</h3>
      <ul class="fa-ul text-lg">
        <li><span class="fa-li"><i class="fas fa-check"></i></span><%= link_to "Devenir arbitre d'escrime", "https://escrime-iledefrance.fr/pratiquer-et-sengager/devenir-arbitre-escrime", target: :blank, class: "hover:font-semibold"%></li>
      </ul>
  </div>
</section>