config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /fr|en/ do
    devise_for :users

    mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

    # Defines the root path route ("/")
    # root "articles#index"
    root to: "pages#home"
    # with namespace admin, all the resource routes will be prefixed with the same
    # starting path /admin
    namespace :admin do
      get '/', to: "admin#index"

      resources :questions do
        resources :answers, only: [:edit, :update]
      end

      resources :lexicons do
        resources :lexicon_answers, only: [:edit, :update]
      end

      resources :lexicons_results, only: [:index]
    end

    get "/ressources", to: "pages#ressources"
    get "qcm", to: "questions#qcm"
    get "/missed_questions", to: "questions#missed_questions"

    resources :questions, only: [:index]  do
      member do
        get 'add_failed_question'
        get 'destroy_failed_question'
      end
      collection do
        post 'add_failed_questions'
        post 'destroy_failed_questions'
      end
    end

    resources :lexicons, only: [:index] do
      # url /lexicons/qcm
      collection do
        get "qcm", to: "lexicons#qcm"
        post "add_lexicon_result"
      end
    end
  end
end

app/views/admin/admin/index.html.erb
<section class="flex flex-col w-11/12 md:w-8/12 mx-auto my-10">
  <h1 class="font-bold text-xl mb-8 self-center"> TABLEAU DE BORD ADMINISTRATEUR</h1>
  <div class="flex flex-col">
    <h2 class="font-bold text-xl">Questions Arbitrage</h2>
    <%= link_to "Voir mes questions", admin_questions_path, class: "my-4 font-semibold text-lg hover:text-gray-500" %>
    <%= link_to "Créer une nouvelle question", new_admin_question_path, class: "font-semibold text-lg hover:text-gray-500" %>
  </div>
  <div class="flex flex-col my-8">
    <h2 class="font-bold text-xl">Questions Lexique</h2>
    <%= link_to "Voir les questions", admin_lexicons_path, class: "my-4 font-semibold text-lg hover:text-gray-500" %>
    <%= link_to "Créer une nouvelle question", new_admin_lexicon_path, class: "font-semibold text-lg hover:text-gray-500" %>
  </div>
  <div class="flex flex-col">
    <h2 class="font-bold text-xl">Accéder aux résultats du QCM de Lexique</h2>
    <%= link_to "Voir les résultats", admin_lexicons_results_path, class: "my-4 font-semibold text-lg hover:text-gray-500" %>
  </div>
</section>